config/routes.rb
GameTable::Application.routes.draw do

  post '/games/:secure_room_code/email' => "games#email", :as => "email"
  root 'games#index'
  get '/games/:secure_room_code/reset' => "games#reset", :as => "reset"
  get '/games/checkers' => "games#checkers", :as => "checkers"
  get '/games/chess' => "games#chess", :as => "chess"
  get '/games/backgammon' => "games#backgammon", :as => "backgammon"
  get '/games/chinese_checkers' => "games#chinese_checkers", :as => "chinese_checkers"
  post '/games/tokens/:id/move', :to => 'tokens#move'
  post '/games/tokens/:id/flip', :to => 'tokens#flip'
  get  '/games/:secure_room_code' => 'games#show', :as => "game"

  resources :games, except: [:show, :new]
  post '/games/messages/:secure_room_code', :to => 'messages#create', :as => 'messages'
  post '/games/roll/:secure_room_code', :to => 'messages#dice', :as => 'dice'

  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :board, dependent: :destroy
  has_many :tokens, dependent: :destroy
  has_many :messages, dependent: :destroy
  #has_many :users

  def self.secure_room_code
     SecureRandom.hex
  end

  def reset
    send("reset_#{self.name}")
  end

  def reset_checkers
    GameBuilder.build_checkers(self)
  end

  def reset_backgammon
    GameBuilder.build_backgammon(self)
  end

  def reset_chess
    GameBuilder.build_chess(self)
  end

  def reset_chinese_checkers
    GameBuilder.build_chinese_checkers(self)
  end

  def self.delete
    Game.where("created_at <= ?", Chronic.parse("one week ago")).destroy
    #games from one week ago or older
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :reset, :email]

  def index
    @games = Game.all

  end

  def checkers 
    @checkers = GameBuilder.build_checkers
    redirect_to game_path(@checkers.secure_room_code)
  end

  def chess
    @chess = GameBuilder.build_chess
    redirect_to game_path(@chess.secure_room_code)
  end

  def backgammon
    @backgammon = GameBuilder.build_backgammon
    redirect_to game_path(@backgammon.secure_room_code)
  end

  def chinese_checkers
    @chinese_checkers = GameBuilder.build_chinese_checkers
    redirect_to game_path(@chinese_checkers.secure_room_code)
  end

  def email
    GameMailer.game_email(@game, params[:email]).deliver
    redirect_to :back
  end

  def reset
    @game.reset
    redirect_to game_path(@game.secure_room_code)
  end

  def show

  end

  def new
    @game = Game.new

  end

  def create
    @game = Game.create(game_params)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find_by(secure_room_code: params[:secure_room_code])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :secure_room_code)
    end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<div class="index-total">

<!--   <div class="games ongoing">
    <h2>Ongoing games</h2>
    <ul>
      <%# @games.each do |game| %>
        <li><%#= link_to game.name, game_path(game.secure_room_code) %></li><br>
      <%# end %>
    </ul>
  </div> -->

<div class="eternity-form">
  <div class="forgot-password-section animated fadeInDown">
    <div class="section-title"><h1>GameTable</h1></div>
      <div class="forgot-content">
        <form>
        <div class="textbox-wrap">
          <div class="input-group input-group-lg col-lg-12">
            <p class="about-p"><strong>GameTable</strong> is a table top gaming platform that lets you play classic board games. Generate a new game and invite your friends to play!</p>
          </div>
        </div>
        <div class="forgot-form-action clearfix">
          <div class="input-group input-group-lg">
            <%= link_to "Checkers", checkers_path, class: "btn btn-success btn-lg" %><br>
            <%= link_to "Chess", chess_path, class: "btn btn-success btn-lg" %><br>
            <%= link_to "Backgammon", backgammon_path, class: "btn btn-success btn-lg" %>
            <%= link_to "Chinese Checkers", chinese_checkers_path, class: "btn btn-success btn-lg" %>
          </div>
        </div>
      </form>
      </div>
  </div>
</div>

<footer class="footer" role="contentinfo">
    <div class="nav navbar-nav twitter">
      <span class="footer-text">Built with ♥ by 
        <a href="https://twitter.com/j_scag_" target="_blank">@j_scag_</a>,
        <a href="https://twitter.com/jamesjtong" target="_blank">@jamesjtong</a>,
        <a href="https://twitter.com/ivanbrennan" target="_blank">@ivanbrennan</a>,
        <a href="https://twitter.com/richardsonjm" target="_blank">@richardsonjm</a>, and 
        <a href="https://twitter.com/ahimmelstoss" target="_blank">@ahimmelstoss</a>.
      </span>
    </div>
    
    <ul class="nav navbar-nav navbar-right footer-links">
      <li><a href="/">Home</a> </li>
      <li><a href="/about">About</a></li>
    </ul>
</footer>
</div>

app/views/games/new.html.erb
<h1>Create a New Game</h1>

<%= form_for(@game) do |f| %>



<%= f.submit "Create" %>


<% end %>

<br><br>
<%= link_to 'Back', games_path %>

<!-- add a select box once game type column is added so users can choose which board setup(chess, checkers, backgammon) -->

app/views/games/show.html.erb
<div class="loading-box">
  <h1>Loading...</h1>
</div>

<div class="main-area">
  <div class="alert alert-warning alert-dismissable alert-whatevs-im-tired">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <p>Be sure to enter your screen name!</p>
  </div>

  <div class="chat">
    <div class="chat-header">
      <h2>Chat</h2>
    </div>
    <div class="messages-box">
      <ul id="chat">
        <% @game.messages.each do |message| %>
          <%= sync partial: 'message', resource: message %>
        <% end %>
        <%= sync_new partial: 'message', resource: Message.new, scope: @game %>
      </ul>
    </div>
      
    <div class="message-input">
      <%= form_for Message.new do |f| %>
        <%= f.text_field :name, :placeholder => "Screen name" %>
        <%= f.text_area :content, :rows => "4" %>
        <% if @game.name == "backgammon" %>
          <div class="button-box">
            <%= f.submit "Send", class: "btn btn-success btn-lg signup" %>
              <%= link_to "Roll Dice!", "/games/roll/#{@game.secure_room_code}", method: "post", class: "btn btn-success btn-lg signup dice-roll" %>
          </div>
        <% else %>
          <div class="normal-send">
            <%= f.submit "Send", class: "btn btn-success btn-lg" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="tabletop">
    <div class="truecenter">
      <div class="board">
        <img src="<%= image_path(@game.board.image) %>">
        <% @game.tokens.each do |token| %>
          <%= sync partial: 'token', resource: token %>
        <% end %>
      </div>
    </div>
  </div>
   <%= form_tag(email_path, method: "post", remote: true) do %>
      <input type="text" name="email" placeholder="your friend's email">
      <%= submit_tag("Invite friends", :class => "btn btn-success btn-md") %>
  <% end %> 

  <div class="menu">

    <div class="btn-group">
        <a class="btn dropdown-toggle btn-mini btn-success" data-toggle="dropdown" href="#">
          Menu
          <span class="caret"></span>
        </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Reset Game", reset_path(@game.secure_room_code), data: { confirm: "Are you sure?" } %></li>
        <li><%= link_to "Home", root_path %></li>
      </ul>
    </div>

  </div>

</div>